# keytool -genkey -alias yyds -keyalg RSA -keypass 2wsx#EDC -keystore yyds.jks -storepass 4rfv#EDC
server:
  port: 8092
spring:
  application:
    name: yyds-uaa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.33.190.195:48366/yyds_uaa?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: cli_users
    password: KJDjifdf343A
    hikari:
      # 连接池名称，HikariPool-1
      pool-name: HikariCP
      # 自动提交从池中返回的连接
      auto-commit: true
      # 池中维护的最小空闲连接数，默认10
      minimum-idle: 5
      # 连接允许在池中闲置的最长时间，默认600000（10min）
      idle-timeout: 600000
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 20
      # 池中最长连接生命周期，默认1800000（30min）
      max-lifetime: 1800000
      # 从池中获取连接等待超时毫秒数，默认30000（30sec）
      connection-timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: icu.oo7.yyds.uaa.domain
  global-config:
    db-config:
      id-type: auto
feign:
  # 使用Okhttp替代feign底层JDK原生的URLConnection
  okhttp:
    enabled: true
  # 开启请求压缩
  compression:
    request:
      enabled: true
      # 可以被压缩的内容
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 # 超过2048字节进行压缩
  # 开启 sentinel 熔断降级
  sentinel:
    enabled: true